<?php
/**
 * @file
 * This is an example outlining how a module can make use backbone.
 */

/**
 * Implements hook_menu().
 *
 * Set up calls to drupal_get_form() for all our example cases.
 */
function backbone_todo_menu() {
  $items = array();

  $items['backbone-todo'] = array(
    'title' => 'Backbone todo',
    'page callback' => 'backbone_todo_page',
    'access callback' => TRUE,
  );

  $items['backbone-todo/list'] = array(
    'title' => 'Backbone todo',
    'page callback' => 'backbone_todo_list',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Load todolist app
 */
function backbone_todo_page() {
  return 'lorem ipsum';
}

/**
 * Load todolist data
 */
function backbone_todo_list() {
  $items = db_query("SELECT * FROM {backbone_todo}")->fetchAll();

  echo json_encode($items);
  exit();
}
