<?php
/**
 * @file
 * This is an example outlining how a module can make use backbone.
 */

/**
 * Implements hook_menu().
 *
 * Set up calls to drupal_get_form() for all our example cases.
 */
function backbone_todo_menu() {
  $items = array();

  $items['backbone-todo'] = array(
    'title' => 'Backbone todo',
    'page callback' => 'backbone_todo_page',
    'access callback' => TRUE,
  );

  $items['backbone-todo/list'] = array(
    'title' => 'Backbone todo',
    'page callback' => 'backbone_todo_list',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Load todolist app
 */
function backbone_todo_page() {
  drupal_add_library('backbone_todo', 'backbone_todo');
  return 'lorem ipsum';
}

/**
 * Load todolist data
 */
function backbone_todo_list() {
  $items = db_query("SELECT * FROM {backbone_todo}")->fetchAll();

  echo json_encode($items);
  exit();
}

/**
 *  * Implements hook_library().
 *   */
function backbone_todo_library_info() {
  $path = drupal_get_path('module', 'backbone_todo');

  $options = array(
    'scope' => 'footer',
    'attributes' => array('defer' => TRUE),
  );

  $libraries['backbone_todo'] = array(
    'title' => 'Backbone todo list',
    'website' => 'https://github.com/marcin-wosinek/backbone_todo',
    'version' => '0.1.0',
    'js' => array(
      $path . '/js/todo.js' => $options,
    ),

    'dependencies' => array(
      array('system', 'jquery'),
      array('system', 'underscore'),
      array('system', 'backbone'),
    )
  );

  return $libraries;
}
